apiVersion: v1
kind: Pod
metadata:
  name: techm-cloud
  labels:
    app: ntp-apache
spec:
  containers:
  - name: ntp-server
    image: prabhudoss/techm:ntp-server
    ports:
     - containerPort: 123
       protocol: UDP
    
  - name: apache-server
    image: prabhudoss/techm:techm-apache-server
    ports:
     - containerPort: 80
       protocol: TCP

  imagePullSecrets:
  - name: regcred
